### ISSUE TITLE
Do not clear all timeouts! Clear only your timeouts!

### ISSUE THREAD

**Issue by DmitryTezh** [creativetimofficial/react-notification-alert#6]
Hi Team! On componentWillOnmount you clear all registered timeouts! But you should clear only that timeouts which was created by your component only! I have several registered timeouts in my other components and they are all cleared by your component (when it unmounts) and this bug breaks a lot of my own logic. Could you pls fix this? Thanks.

**Comment by einazare** [comment]
Hello there @DmitryTezh ,

Thank you for telling us about this issue.
I am not sure what we could do about this. 
Do you have any solution?
In the meantime, we'll try to find a solution as well, but all the pages we've found, all tell to clear all timeouts.

Best,
Manu

**Comment by DmitryTezh** [comment]
Hi Manu! Sorry for delay, I was a little bit busy with my projects.
The solution is straightforward - when you call setTimeout in notificationAlert (line 113), you should push its returned id in your array, then in componentWillOnmount you should iterate over this array and call clearTimeout only for its items (ids).
Thanks.

**Comment by DmitryTezh** [comment]
One more important thing - this array should be a private field on class level to prevent iterference with another component instances.

**Comment by einazare** [comment]
Hello, @DmitryTezh ,

I'll try to make an update today, if not, then the update will be done on next Monday.
Thank you for sharing this with us.

Best,
Manu

**Comment by DmitryTezh** [comment]
Hi Manu!
Thank you for prompt update! Looking forward to getting a fix!

**Comment by einazare** [comment]
Hello again @DmitryTezh ,

Just updated the plugin.
It should now work.
```
npm i -E react-notification-alert
```

Best,
Manu

**Comment by DmitryTezh** [comment]
Hi Manu! Sorry, but nothing has been changed. The issue still exists for me. Thanks.

**Comment by einazare** [comment]
Hello again, @DmitryTezh ,

I think by mistake I've deleted the code for this issue.
I do not understand how stupid should I be to do this :)) . 
Really sorry about this.
I'll make again the update these days, and this time I'll check to see if the code was pushed on Github and npm appropriately.

Best,
Manu

**Comment by DmitryTezh** [comment]
Hi Manu! Don't worry, such happens... Waiting for update. Thanks.

**Comment by einazare** [comment]
Hello again @DmitryTezh ,

I've just made yet again an update.
Sorry for taking this long.
Now everything should be fine.
```
npm i -E react-notification-alert
```

Best,
Manu

**Comment by DmitryTezh** [comment]
Hi Manu! Confirmed, it works now! Thank you!
